# config.yaml
app:
  debug: true
  secret_key: 'your_secret_key'
  database:
    uri: 'sqlite:///your_database.db'


dependencies:
  - flask: 2.3.0
  - requests: 2.28.1
  - numpy: 1.21.0
  - pandas: 1.3.3
  
