# This is a basic workflow to help you get started with Actions

name: Group Portfolio

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Create and activate the virtual environment, install dependencies, and run the app
      - name: Set up Python environment and run app
        run: |
          #!/bin/bash

          # Activate virtual environment
          if [ ! -d "venv" ]; then
              echo "Virtual environment not found. Creating one..."
              python3 -m venv venv
          fi

          source venv/bin/activate

          # Install required packages
          if [ -f "requirements.txt" ]; then
              echo "Installing dependencies from requirements.txt..."
              pip install -r requirements.txt
          else
              echo "Error: requirements.txt not found!"
              exit 1
          fi

          # Run the app
          echo "Starting the application..."
          python app.py

          # Make the script executable
          chmod +x build.sh

          # Start the app (optional if calling this script directly)
          echo "Build script executed successfully."
